version: '3.1'
services:
  app:
    container_name: employee-db-manager
    image: employee-db-manager
    build: ./
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb
