version: '2'
services:
  app:
    container_name: employee-proxy
    image: employee-proxy
    build: ./
    ports:
      - "8081:8081"
  employee-db-manager:
    image: employee-db-manager
    container_name: employee-db-manager
    ports:
      - "8083:8083"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employeedb
